/* eslint-disable */
<template>
  <div>
    <div class="page-wrapper">
      <!-- Preloader -->
      <div class="preloader">
        <div class="icon" />
      </div>

      <!-- Main Header -->
      <Header />
      <!-- End Main Header -->

      <!--Search Popup-->
      <SearchPopup />

      <div>
        <!-- Banner Section -->

        <section class="banner-section banner-one">
          <div class="dashboard-inner" style="background-color:#FFFFFF; height: 400px;" :style="{ backgroundImage: `url(${backgroundUrl})` }">
            <!--            <canvas id="dashboard-report" />-->
            <div class="h-100 d-flex justify-content-center align-items-center flex-column">
              <div class="w-100 text-center africa-global-city text-uppercase">
                oil & gas
              </div>
              <!--              <div-->
              <!--                class="mt-3"-->
              <!--                style="font-style: normal;-->
              <!--                       font-weight: normal;-->
              <!--                       font-size: 32px;-->
              <!--                      line-height: 153%;-->
              <!--                      text-align: center;-->
              <!--                      color: #FFFFFF;"-->
              <!--              >-->
              <!--                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <br> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <br> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->
              <!--              </div>-->
            </div>
          </div>
          <!-- Slide Item -->
        </section>

        <!--End Banner Section -->

        <!--Facts Section-->
        <section class="about-section" style="background-color: #FAFAFF">
          <div class="auto-container">
            <div class="row oil-body1">
              <div class="col-sm-6">
                <div class="oil-header1">
                  What is IOGC?
                </div>
                <div class="mt-4">
                  IBILE Oil and Gas Corporation (IOGC) is Lagos State's commercial oil and gas entity established in 2013 to invest and engage in oil and gas activities with a focus on ensuring energy sustainability and security along the energy value chain. and to deepen the use of cleaner fuels in the state.
                </div>
                <div class="mt-4">
                  It’s vision is to become a commercially viable entity, contributing to Lagos State economic development and GDP growth.
                </div>
                <div class="mt-4">
                  IOGC is committed to a high level of corporate governance and promoting a culture that values ethical behaviour, integrity and respect. We believe that adopting and operating in accordance with high standards of corporate governance is essential for sustainable long­ term performance and value creation
                </div>
              </div>
              <div class="col-sm-6 p-5">
                <img src="~/assets/images/oil-img1.png">
              </div>
            </div>
          </div>
        </section>
        <section class="about-section" style="background-color: white">
          <div class="auto-container">
            <div class="row oil-body1">
              <div class="col-sm-4 p-5 oil-header1 d-flex align-items-center justify-content-center" style="color: #233566">
                Lagos gas economy
              </div>
              <div class="col-sm-8">
                <div class="mt-4">
                  Nigeria currently consumes about 4000 MW in electrical power daily, largely generated by turbines (gas and hydro powered) and thermal stations. About 30% of this is consumed by residences , industries and other places of commerce in Lagos. This remains inadequate for the power needs of the state and is typically augmented for household, commercial and transportation use by burning of dirty fuel (charcoal and other petroleum derived fuel).
                </div>
                <div class="mt-4">
                  Nigeria has ratified the Paris Climate Change Agreement with plans to reduce emissions by 45% in 2022. With over 22 million Nigerians still dependent on solid fuel which causes the nation to lose between 350,000 and 400,000 hectares of land to deforestation every year and approximately 80,000 deaths.
                </div>
                <div class="mt-4">
                  At a period when there is a growing global consciousness around the negative socio-economic impact of the long-term use of dirty fuel on the environment and human lives; with discussions centred around switching to more environment friendly alternatives, IOG C not only seeks to create a profitable gas (LPG, LNG, CNG) venture to meet the needs of the state, but also to foster development targeted at reducing the carbon foot print of Lagos which is imperative to creating a healt hy environment for its continuously increasing populace and building a sustainable Lagos. Nigeria also has the opportunity to showcase Lagos as its flagship gas economy in addition to the other selected pilot states as gas will accelerate the transition of Nigeria to a post-oil era.
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="about-section" style="background-color: #FAFAFF">
          <div class="auto-container">
            <div class="row oil-body1">
              <div class="col-sm-5">
                <img src="~/assets/images/oil-img2.png">
              </div>
              <div class="col-sm-7">
                <div class="oil-header1" style="color: #233566;">
                  gas commercialisation
                </div>
                <div class="mt-4">
                  Gas is the catalyst for economic growth and environmental sustainability for Lagos State. Our objectives are to:
                </div>
                <div class="mt-4">
                  Promote gas as a clean burning fuel that provides smoke free indoor cooking and can also help reduce outdoor and urban air pollution
                </div>
                <div class="mt-4">
                  Increase LPG household usage from 35% to 80% by 2023
                </div>
                <div class="mt-4">
                  Promote gas as a fuel for transportation
                </div>
                <div class="mt-4">
                  Use gas will be a driver for economic growth andjob creation opportunities
                </div>
                <div class="mt-4">
                  Contribute significant reduction of carbon (CO<sub>2</sub>) emission / footprint (LPG is 50% lower than coal and 20% lower than heating oil)
                </div>
                <div class="mt-4">
                  Enhance quality of life for Lagos residents
                </div>
                <div class="mt-4">
                  These objectives would be met through creating a sustainable and efficient gas value chain, promoting development of gas infrastructurefor transportation, expansion of the utilization of gas for industries in multiple sectors and implementation of policies to regulate and curb dirty fuel usage.
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="about-section" style="background-color: white">
          <div class="auto-container">
            <div class="oil-header1 text-center">
              Proposed Lagos State Gas Value Chain
            </div>
            <div class="align-items-center justify-content-center d-flex mt-5">
              <div class="w-75">
                <img src="~/assets/images/oil-img3.png">
              </div>
            </div>
          </div>
        </section>
        <section class="about-section" style="background-color: #FAFAFF">
          <div class="auto-container">
            <div class="row oil-body1">
              <div class="col-sm-5">
                <img src="~/assets/images/oil-img4.png">
                <div class="text-capitalize font-weight-bold mt-5" style="color: #233566;">
                  Major Gas Cylinder Filling Plants
                </div>
                <div class="mt-4">
                  The goal is to operate a chain of LPG Retail Plants spread within neighb ourhoods across the 5 divisions of Lagos to ensure the availability, accessibility, affordability and acceptability of gas to the end user. These facilities would then give supply to neighbourhood gas skids through our bobtail trucks.
                </div>
              </div>
              <div class="col-sm-7 px-5">
                <div class="text-capitalize font-weight-bold" style="color: #233566;">
                  Neighbourhood Gas Skids and Last-mile Deliveries
                </div>
                <div class="mt-4">
                  We plan to create employment by deepening use through door-2-door delivery model into homes by operating a chain of 20 retail outlets.
                </div>
                <div class="mt-4">
                  The fleet of bob tail trucks will convey gas products from the divisional gas cylinder filling plant s to much  smaller  neighbourhood situated gas skids where they will be retailed, and the skids would be serviced with tricycle shuttles that will make door to door deliveries on request from the end user.
                </div>
                <div class="mt-4">
                  This will lead to an additional 4000 jobs.
                </div>
                <div class="text-capitalize font-weight-bold mt-5" style="color: #233566;">
                  Retail Autogas Stations
                </div>
                <div class="mt-4">
                  IOGC will co-locate gas pumps at it's Retail Filling Stations supplied from the Coastal Gas Storage and Terminal in Badagry, where vehicles can easily drive in and purchase Autogas. This will require about N3BN in funding.
                </div>
                <div class="mt-4">
                  The value chain created by the implementation of gas for transport will create 100,000 skilled and unskilled jobs, directly and indirectly.
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="banner-section banner-one">
          <div class="dashboard-inner" style="background-color:#FFFFFF; height: fit-content;background-size: 100% 100%;padding-bottom: 70px" :style="{ backgroundImage: `url(${backgroundUrl2})` }">
            <div class="auto-container">
              <div class="oil-header2 pt-5">
                Industry for gas consumption in Lagos by 2023
              </div>
              <div class="row pt-5">
                <div class="col-sm-3">
                  <div class="d-flex align-items-center justify-content-center pt-3">
                    <img src="~/assets/images/oil-icon2.png">
                  </div>
                  <div class="oil-header3 text-center py-2">
                    800,000MT
                  </div>
                  <div class="oil-body2">
                    Homes
                  </div>
                </div>
                <div class="col-sm-3 startup-margin">
                  <div class="d-flex align-items-center justify-content-center pt-3" style="padding-bottom: 12px">
                    <img src="~/assets/images/oil-icon1.png">
                  </div>
                  <div class="oil-header3 text-center py-2">
                    400,000MT
                  </div>
                  <div class="oil-body2">
                    Automobile & Transportation
                  </div>
                </div>
                <div class="col-sm-3 startup-margin">
                  <div class="d-flex align-items-center justify-content-center">
                    <img src="~/assets/images/oil-icon4.png">
                  </div>
                  <div class="oil-header3 text-center py-2">
                    400,000MT
                  </div>
                  <div class="oil-body2">
                    Agro Processing
                  </div>
                </div>
                <div class="col-sm-3 startup-margin">
                  <div class="d-flex align-items-center justify-content-center pt-3 pb-2">
                    <img src="~/assets/images/oil-icon3.png">
                  </div>
                  <div class="oil-header3 text-center py-2">
                    100,000MT
                  </div>
                  <div class="oil-body2">
                    Food & abattoirs
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="about-section" style="background-color: white">
          <div class="auto-container">
            <div class="oil-header1 text-center mb-4" style="color: #233566;">
              Investment opportunities
            </div>
            <div class="row oil-body3">
              <div class="col-sm-4 p-5">
                <div class="oil-header4 py-2">
                  INFRASTRUCTURE
                </div>
                <div class="py-2">
                  Requite about $800,000,000 worth of infrastructure for gas transport and retailing
                </div>
                <div class="py-2">
                  3,000 Gas filling plants
                </div>
                <div class="py-2">
                  Petrochemical plants e.g. glycerine
                </div>
                <div class="py-2">
                  Midstream piping infrastructure for underserved areas of Lagos e.g. Badagry
                </div>
                <div class="py-2">
                  10,000 Trucks (Bobtails, Bridgers)
                </div>
                <div class="py-2">
                  Storage
                </div>
                <div class="py-2">
                  Skids
                </div>
              </div>
              <div class="col-sm-4 p-5">
                <div class="oil-header4 py-2">
                  TARGETS
                </div>
                <div class="py-2 font-weight-bold">
                  Domestic Household Consumption Target
                </div>
                <div class="py-2">
                  Increase use from 300,000 MT to 800,000MT
                </div>
                <div class="py-2">
                  Increase general awareness, acceptability and availability
                </div>
                <div class="py-2">
                  Cylinder injections across the scheme Achieve 48MT of CO<sub>2</sub> reduction .
                </div>
                <div class="py-2 font-weight-bold">
                  Agriculture
                </div>
                <div class="py-2">
                  Achieve 200,000- 400,0000 MT of gas consumption by 2022
                </div>
                <div class="py-2">
                  Through clean mechanized farming by 50% reduction in diesel/fuel consumption reduce CO<sub>2</sub> emission of total agro-processing machinery activities by 50% with gas fired burners, cooling applications for storage and power.
                </div>
              </div>
              <div class="col-sm-4 p-5">
                <div class="oil-header4 py-2 invisible">
                  INFRASTRUCTURE
                </div>
                <div class="py-2 font-weight-bold">
                  Power
                </div>
                <div class="py-2">
                  500,000- 1,000,000 tons of gas to generate 1,000- 2,000 MW of electricity through scalable captive power by 2023
                </div>
                <div class="py-2">
                  Gas to power about 10,000 telco cell sites after launch of SG
                </div>
                <div class="py-2">
                  Impact on manufacturing industry by replacing diesel which is more expensive as a fuel for power.
                </div>
                <div class="py-2">
                  Power LASG offices and public utilities
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>

    <!--End pagewrapper-->

    <!-- Main Footer -->
    <Footer />

    <!--Scroll to top-->
    <ScrollTop />
  </div>
</template>

<script>
import ScrollTop from '@/components/ScrollTop'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import SearchPopup from '../../components/SearchPopup'
import bannerImageOne from '~/assets/images/main-slider/1.jpg'
import bannerImageTwo from '~/assets/images/main-slider/2.jpg'
import bannerImageThree from '~/assets/images/main-slider/3.jpg'
import patternImage from '~/assets/images/background/pattern-1.png'
import testimonialBackground from '~/assets/images/background/image-2.jpg'
import suggestionBackground from '~/assets/images/background/image-5.jpg'
import sanwoOluBackground from '~/assets/images/background/image-1-test.jpg'
import backgroundUrl from '~/assets/images/background/oil30.png'
import backgroundUrl2 from '~/assets/images/background/oil-bi2.png'
import backgroundUrl3 from '~/assets/images/background/ict-bi3.png'
import backgroundUrl4 from '~/assets/images/background/ict-bi4.png'

export default {
  components: {
    ScrollTop,
    Header,
    SearchPopup,
    Footer
  },
  data () {
    return {
      bannerImageOne,
      bannerImageTwo,
      bannerImageThree,
      patternImage,
      testimonialBackground,
      suggestionBackground,
      sanwoOluBackground,
      backgroundUrl,
      backgroundUrl2,
      backgroundUrl3,
      backgroundUrl4
    }
  }
}
</script>

<style>

</style>
