/* eslint-disable */
<template>
  <div>
    <div class="page-wrapper">
      <!-- Preloader -->
      <div class="preloader">
        <div class="icon" />
      </div>

      <!-- Main Header -->
      <Header />
      <!-- End Main Header -->

      <!--Search Popup-->
      <SearchPopup />

      <div>
        <!-- Banner Section -->

        <section class="banner-section banner-one">
          <div class="dashboard-inner" style="background-color:#FFFFFF; height: 400px;" :style="{ backgroundImage: `linear-gradient(303.69deg, rgba(7, 26, 53, 0.7) -9.68%, rgba(25, 53, 102, 0.7) 59.8%), url(${backgroundUrl})` }">
            <!--            <canvas id="dashboard-report" />-->
            <div class="h-100 d-flex justify-content-center align-items-center">
              <div class="w-100 text-center africa-global-city">
                LAGOS AT A GLANCE
              </div>
            </div>
          </div>
          <!-- Slide Item -->
        </section>

        <!--End Banner Section -->

        <!--Facts Section-->
        <section id="history" class="about-section" style="background-color: #F5FBFF">
          <div class="auto-container">
            <div class="row">
              <div
                class="col-sm-4"
              >
                <img src="~/assets/images/glace_history.png" class="img-fluid">
              </div>
              <div
                class="col-sm-8  d-flex flex-column align-items-start text-dark pt-4 pl-5"
              >
                <div class="focal-sector-h mb-2">
                  History
                </div>
                Lagos is the commercial capital of Nigeria and the economic hub of West Africa.
                Lagos State was created on May 27, 1967 and became the federal capital of Nigeria on April 11, 1968. It remained the capital until 1991 when the government seat was moved to the Federal Capital Territory, Abuja. In spite of the movement of the capital to Abuja, Lagos still remains the commercial capital of the country and the economic hub of West Africa to date.

                <div class="row w-100">
                  <div class="col-sm-4 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-25">
                      <img src="~/assets/images/location.png" height="40px">
                    </div>
                    <div class="w-75">
                      <div class="font-weight-bold">
                        Location
                      </div>
                      <div>
                        Location West Nigeria
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-4 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-25">
                      <img src="~/assets/images/bar-chart.png" height="40px">
                    </div>
                    <div class="w-75">
                      <div class="font-weight-bold">
                        GDP
                      </div>
                      <div>
                        GDP $136.6 billion (2015)
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-4 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-25">
                      <img src="~/assets/images/population.png" height="40px">
                    </div>
                    <div class="w-75">
                      <div class="font-weight-bold">
                        Population
                      </div>
                      <div>
                        Population 21 million est.(2014)
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <!--End Banner Section -->

        <!--Facts Section-->
        <section id="economy" class="about-section" style="background-color: #F5FBFF">
          <div class="auto-container">
            <div class="row">
              <div
                class="col-sm-8  d-flex flex-column align-items-start text-dark pt-4 pl-5"
              >
                <div class="focal-sector-h mb-2">
                  The Economy
                </div>
                The GDP of the formal economy of Lagos is estimated to be $136.6 billion contributing 30% to the GDP of Nigeria as at August 2015. The GDP has an estimated growth rate of 10% and it is expected that by 2025 the GDP will be $355billion.
                Lagos State's Internally Generated Revenue (IGR) for 2014 was approximately $1.4billion. more than three times the amount generated by Rivers State. the second highest state.
                The high IGR positions Lagos for strong growth. thereby improving the standard ofiiving and incomes of the population to further boost the state's economy. It currently takes 25 days to start a business in Lagos and over the last year. the ease of getting credit has improved by 30%, thereby easing the process of investing in Lagos.

                <div class="row w-100">
                  <div class="col-sm-6 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-25">
                      <img src="~/assets/images/currency-exchange.png" height="40px">
                    </div>
                    <div class="w-75">
                      <div class="font-weight-bold">
                        Exchange Rate
                      </div>
                      <div>
                        $1 - N305.00 (December 2017)
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-25">
                      <img src="~/assets/images/analytics.png" height="40px">
                    </div>
                    <div class="w-75">
                      <div class="font-weight-bold">
                        GDP per Capital
                      </div>
                      <div>
                        $3. 7 43.90 (2017)est.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="col-sm-4"
              >
                <img src="~/assets/images/economy30.png" class="img-fluid">
              </div>
            </div>
          </div>
        </section>

        <section id="population" class="about-section" style="background-color: #F5FBFF">
          <div class="auto-container">
            <div class="row">
              <div
                class="col-sm-4"
              >
                <img src="~/assets/images/population30.png" class="img-fluid">
              </div>
              <div
                class="col-sm-8  d-flex flex-column align-items-start text-dark pl-5"
              >
                <div class="focal-sector-h mb-2" style="color: #9F11E2">
                  Population
                </div>
                Lagos is currently the most populous city in Africa
                Lagos State has a population of21 million as atJanuary 2015, making it Africa's largest city and the 3rd largest city in the world. The population has an average annual growth rate of 3.2%and is estimated to be over 30 million by 2025. This large population creates a viable market for manufacturing and retail of consumer goods and other services. Lagos also happens to be the most learned state in Nigeria with over 45% of the skilled manpower in Nigeria located in Lagos. The state has a literacy rate of 92% that is significantly higher than the national average of 56%.
                <div class="row w-100">
                  <div class="col-sm-12 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-100">
                      <img src="~/assets/images/glance-population.png" height="40px">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="business" class="about-section" style="background-color: #F5FBFF">
          <div class="auto-container">
            <div class="row">
              <div
                class="col-sm-8  d-flex flex-column align-items-start text-dark pt-4 pl-5"
              >
                <div class="focal-sector-h mb-2" style="color: #7CC247">
                  Business Climate
                </div>
                Lagos State fosters a conducive environment that allows businesses to thrive

                <div class="row w-100">
                  <div class="col-sm-6 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-100">
                      <div class="font-weight-bold text-center" style="font-size: 47px;">
                        60%
                      </div>
                      <div class="mt-5">
                        (approx.) of industrial investments in Nigeria come into Lagos State
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6 d-flex align-items-center justify-content-center mt-5">
                    <div class="w-100">
                      <div class="font-weight-bold" style="font-size: 47px;">
                        90%
                      </div>
                      <div class="mt-5">
                        of companies in Nigeria across most industries have chosen to locate their headquarters in Lagos.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="col-sm-4"
              >
                <img src="~/assets/images/glance-climate.png" class="img-fluid">
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>

    <!--End pagewrapper-->

    <!-- Main Footer -->
    <Footer />

    <!--Scroll to top-->
    <ScrollTop />
  </div>
</template>

<script>
import ScrollTop from '@/components/ScrollTop'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import SearchPopup from '../../components/SearchPopup'
import bannerImageOne from '~/assets/images/main-slider/1.jpg'
import bannerImageTwo from '~/assets/images/main-slider/2.jpg'
import bannerImageThree from '~/assets/images/main-slider/3.jpg'
import patternImage from '~/assets/images/background/pattern-1.png'
import testimonialBackground from '~/assets/images/background/image-2.jpg'
import suggestionBackground from '~/assets/images/background/image-5.jpg'
import sanwoOluBackground from '~/assets/images/background/image-1-test.jpg'
import backgroundUrl from '~/assets/images/background/glancelagos.png'

export default {
  components: {
    ScrollTop,
    Header,
    SearchPopup,
    Footer
  },
  data () {
    return {
      bannerImageOne,
      bannerImageTwo,
      bannerImageThree,
      patternImage,
      testimonialBackground,
      suggestionBackground,
      sanwoOluBackground,
      backgroundUrl
    }
  }
}
</script>

<style>

</style>
